// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GftpClient is the client API for Gftp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GftpClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type gftpClient struct {
	cc grpc.ClientConnInterface
}

func NewGftpClient(cc grpc.ClientConnInterface) GftpClient {
	return &gftpClient{cc}
}

func (c *gftpClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/gftp.Gftp/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GftpServer is the server API for Gftp service.
// All implementations must embed UnimplementedGftpServer
// for forward compatibility
type GftpServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedGftpServer()
}

// UnimplementedGftpServer must be embedded to have forward compatible implementations.
type UnimplementedGftpServer struct {
}

func (UnimplementedGftpServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGftpServer) mustEmbedUnimplementedGftpServer() {}

// UnsafeGftpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GftpServer will
// result in compilation errors.
type UnsafeGftpServer interface {
	mustEmbedUnimplementedGftpServer()
}

func RegisterGftpServer(s grpc.ServiceRegistrar, srv GftpServer) {
	s.RegisterService(&Gftp_ServiceDesc, srv)
}

func _Gftp_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GftpServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gftp.Gftp/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GftpServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gftp_ServiceDesc is the grpc.ServiceDesc for Gftp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gftp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gftp.Gftp",
	HandlerType: (*GftpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Gftp_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gftp.proto",
}
